language: python
python:
- 2.7.18
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
- provider: heroku
  api_key:
    secure: U0/DC4noIYF0ZvPkfCqDHhuitcD2sLyrKBETUgtAIqZEQhel4YBfnQK3YyHLWys7o5kW51qksm+ZhdnIlU9baUX4UlOVEOGCqV3WiwHeHVDJsRgM0eNDxw3U9OWKMdDt2TvTMjD0GoAxu4Bch0EWgRSi4LeQcIju6qX6fkHWE1fTn6kLBzSCPkzkoB9mivw19Ok26s7lCSgnLMhNceYr/Xb3pucrcOfMM/HGqb33GwiEkh5o4YJ3DCblctKdFqckbECy4X0a2ToVOk7nXbdxEfVhAln7kFliR5+IITKR3MwYBL5vRqzC10PtJ5lNr6T7DLbARCcQXi4EAYEum3zaJTKU0L2T1FSwbwsBTEtCn6Ekjj0m9N9k0/h6u0O3RUaOjIBlrmlSrcl6nJ8//0bqKkfj/HGOiikqQvITrB4V3lM23SFPFZTQAuyIU2y+1uroSxhEEuMH6bIPzY7mUXUL2gN3/qf3kP8yTE0GoOdB7Uru+y81gf+LBFVXMf4jynEBFdBuS7E1zQq3rzWBlIUHRUWNFn9HY8doNrKkz6ZPRlwd4C/2kG3DfY9VFpY+kqtYv/IK0w4s68ciSow1xxKF/T/cD2dMlxKTaBAGT1UMqcIPccrUrnyuKbLWsUB+uoc8vPufj06gMr7a3344lFOjMBesRTOPwW8EY+VOOb6o4Ak=
  app: dipak-scanexe
