language: python
python:
- 2.7.18
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
- provider: heroku
  api_key:
    secure: nDEvHK/hn8FEzT10mt330CTK3LpqdLGFDthanc9WOqS8/VrBN+wKlMDroBR1hninANg6EJLxQGjpryiWKGnNbwWgK29Y40UYWsbeoZYlyzt5aXRf4ZksyxPZB2AFVWNU4Rti2GxiChQWpLLYbL6YSKe1oqYtJF8SW5Ypqv0T7/DaNU2CG839lUsm8Y0kdYx/Tj/bu4KRdPKsBda0IZJQzMRG6zZHKGjoPva66nr9DiaQQYVU0TpbRuF98qeHUx1/trNsXUIJos1jZ49rpxPEq1LjBBMRSVKeyZ9oTMFjDfwgMMIkQ6+QZl0tvw0189M36ui/Ej5K12LMXDD+Ycl0Acre2EfAm7iYN+PjpK9+YeOPp3PxcNZTZHhbQD4SWecBCvYZQQBzkUiw6+3N9IDrQIdkm46QNendem5Gsq7xgRVzINEYBKqf57Sbe8hg0VG579lQS3SaHe7+7JQtCAPqxbr0rxS6LcBiJASehXnPc+o7B6XmGqIScXqJINQkK93jUIwyngHmQGSrB9n7akFJe3o6QMtR9cXQFQ/dK2BsrBMHFNMCTVGmgoAqzedzgsSjpN2BgDls52229d9iKV4mV6QcKV7xa4VkOM/Ox1hRSHRURyt5yxGzQLjQRklTFYCvuVyjYA5ZDVzLWt2peUJFFvMdC9IIhRuijdWizQbpmnw=
  app: dipak-scanexe
