language: python
python:
- 2.7
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
- provider: heroku
  api_key:
    secure: g5hY0vSn5rdUdSUxqz+1rrySN5Cc5iRNq8gjfjBmrWRKJMo0d0zx/t4kG08lKw9fE2vw2Le6SiJIYA6E8JnO7IbujNwjoOIMwzew5N+NfYynRVMCLlAss4wJHHl1SVdtqXCwYAOdfwhAOFP4FAfbqGdJ4gg+Q/7kTkKswXoBjrKCKLlSumBshAn8M+YQ8FF15bt6G+Q3mI/Af1LZ0eOe2AxNqdnxsz+bx+aFa3nJ6jz46+ARazRALFR1oNYGzP1GDVEW+KQ0ZwgpF1r/QIYHuic3xfoCtB5WA8i5/OGb764NgvWQzRFZdEuQma/Do0KCUGuyiseNf4Ow4lIgP4UfMAXfCeABBMzFChIUpVuKMdVH0zIe/8HFuAlDEcuplySUzdHSoWpfWBV8A7xh9UeMOgrumIxPI2emJiIwyxIsdIXFgEwbxroS2tThpeBaVUAZTMKOYZUTlyWAi1vzxFDDB/CO9g+Ut5FnOjZ+Wapa/GpK6h1wc0uL2nVFyGO4DN4ry8RSHyulrgwwNcYBTXYiXMfQ2b5k0V4Wvg+TBbNCIVlG05PwWYMKtNypIhNqUfx0qkGnVOL3Py955DMnk/+9LPEh0yRc5Hk66x5VCkUFKjobjBL1z81Q3ihGH/9quNWMUZ2L3RAzR4leHJxtM2AIOygz8fzsoWJcv8Pi3iDvUw8=
  app: dipak-scanexe
