language: python
python:
- 2.7.18
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
- provider: heroku
  api_key:
    secure: Gkwa9wUWpwhHbAJdTxDF3BgQ2JMvSULwQhVwYE/VK0GNn85aQ+7h/ieORRQtYmtTac5mf2O91D4G/YRUN0sIHZCnh5sjuAcv0WWHP5gDvaPkzmcrKZwdj/H3wNZ9F0BP100zSRnHKz3Q8e1wR+4Pl6Yt/2dCYcPtzVumGEJiK3gFll12k+rq/KCDWH+XzFwWUfHveUOsDWSDYCyhwcctmKLaA5YjyPQ6AA1xz4vai4jIKQktfK0xHXx8Us1jZi7m71DRKblt6jLOo7vHkPe/0UD5hHPPhIdI/k+HmxSffp1nqCMn0Igy0oHyGl9d47XP22TajJqhAxfZ3RN9sLKx2VTyj07cDRwVq05RvlSDhCtq3PwmlmBDdzzzQ2r5GGaDy380yStzJMvg3NnxGLgJKQ3sBKFYN9IN6UMsgJFGMyuhah2C0A7Xb6QVVjcQe5fjiQR0r9sppYgZeZitSX759rivnfxjsPibokgD8PeTn4YtBLwQF5pqrzg4T26gSrPjV3o7aj9iHZG9/BlvMu+dT+OHdup6tgld4r22bYdLxitw75eKKgoolb1zB27v2ExaZWilPmTX+mvC1gtOFnZUbllybySplmX0D1MIA0/DCC8EKqs0giYUW3Z47G90P39Dr63iZPoE/eeQhWf1aTgzKx381phU6/Szii5Z+bd/yM0=
  app: dipak-scanexe
